In [1]:
import pandas as pd
import numpy as np

## Question 1
What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [2]:
pd.__version__

'2.0.3'

Getting the data
For this homework, we'll use the California Housing Prices dataset. Download it from here.

You can do it with wget:

wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Or just open it with your browser and click "Save as...".

Now read it with Pandas.



## Question 2
How many columns are in the dataset?

In [3]:
df = pd.read_csv("raw.githubusercontent.com_alexeygrigorev_datasets_master_housing.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


## Question 3
Which columns in the dataset have missing values?

In [4]:
df.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

## Question 4
How many unique values does the ocean_proximity column have?

In [9]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

## Question 4
How many unique values does the ocean_proximity column have?

In [6]:
df[df["ocean_proximity"] == "NEAR BAY"].median_house_value.mean()


259212.31179039303

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


## Question 6
1. Calculate the average of **total_bedrooms** column in the dataset.
2. Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
3. Now, calculate the average of total_bedrooms again.
4. Has it changed?

Hint: take into account only 3 digits after the decimal point.

In [57]:
# 1- 
mean_avg = df.total_bedrooms.mean().round(3)
mean_avg

537.871

In [67]:
# 2-
df.total_bedrooms = df.total_bedrooms.fillna(537.871)
df.total_bedrooms.mode()

0    537.871
Name: total_bedrooms, dtype: float64

In [68]:
# 3- 
mean_avg = df.total_bedrooms.mean().round(3)
mean_avg

537.871

It has the same value.

## Question 7
1. Select all the options located on islands.
2. Select only columns **housing_median_age, total_rooms, total_bedrooms**.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [950, 1300, 800, 1000, 1300].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the last element of w?

Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [46]:
# df.info()

In [97]:
#1-  &  2-
new_df = df[df["ocean_proximity"] == "ISLAND"][["housing_median_age", "total_rooms", "total_bedrooms"]]
new_df

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [98]:
x = new_df.values
x

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [99]:
x_transposed = x.T
x_transposed

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [101]:
XTX = x_transposed.dot(x)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [102]:
inv_XTX = np.linalg.inv(XTX)
inv_XTX

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [94]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [103]:
w = inv_XTX.dot(x_transposed).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])